/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCoachRouteImport } from './routes/api/coach'
import { Route as ApiDossierRouteImport } from './routes/api/dossier'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoachRoute = ApiCoachRouteImport.update({
  id: '/api/coach',
  path: '/api/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDossierRoute = ApiDossierRouteImport.update({
  id: '/api/dossier',
  path: '/api/dossier',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/dossier': typeof ApiDossierRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/dossier': typeof ApiDossierRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/coach': typeof ApiCoachRoute
  '/api/dossier': typeof ApiDossierRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/coach' | '/api/dossier'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/coach' | '/api/dossier'
  id: '__root__' | '/' | '/api/coach' | '/api/dossier'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCoachRoute: typeof ApiCoachRoute
  ApiDossierRoute: typeof ApiDossierRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/coach': {
      id: '/api/coach'
      path: '/api/coach'
      fullPath: '/api/coach'
      preLoaderRoute: typeof ApiCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dossier': {
      id: '/api/dossier'
      path: '/api/dossier'
      fullPath: '/api/dossier'
      preLoaderRoute: typeof ApiDossierRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCoachRoute: ApiCoachRoute,
  ApiDossierRoute: ApiDossierRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
